/**
 * lib/registry.js — Master Calculator Registry
 * All 219 calculators with slug, name, category, description
 */

export const CATEGORIES = [
  { id: 'tax',        label: 'Tax',                emoji: '🧾', color: 'green'  },
  { id: 'loans',      label: 'Loans & EMI',         emoji: '🏦', color: 'blue'   },
  { id: 'invest',     label: 'Investments',          emoji: '📈', color: 'amber'  },
  { id: 'insurance',  label: 'Insurance',            emoji: '🛡️', color: 'red'    },
  { id: 'realty',     label: 'Real Estate',          emoji: '🏠', color: 'purple' },
  { id: 'business',   label: 'Business & GST',       emoji: '💼', color: 'pink'   },
  { id: 'utility',    label: 'Utility & Lifestyle',  emoji: '⚡', color: 'teal'   },
  { id: 'nri',        label: 'NRI Calculators',      emoji: '✈️', color: 'orange' },
  { id: 'stocks',     label: 'Stock & Trading',      emoji: '📊', color: 'sky'    },
  { id: 'govt',       label: 'Govt Schemes',         emoji: '🏛️', color: 'indigo' },
  { id: 'education',  label: 'Education & Career',   emoji: '🎓', color: 'violet' },
  { id: 'credit',     label: 'Credit & Cards',       emoji: '💳', color: 'rose'   },
  { id: 'intl',       label: 'International',        emoji: '🌍', color: 'slate'  },
]

export const CALCULATORS = [
  // ── TAX (30) ──────────────────────────────────────────────────
  { slug: 'income-tax',           cat: 'tax',    name: 'Income Tax Calculator',      desc: 'New vs Old Regime FY 2026-27',         popular: true  },
  { slug: 'take-home-salary',     cat: 'tax',    name: 'Take-Home Salary',           desc: 'CTC to in-hand breakdown',             popular: true  },
  { slug: 'old-vs-new-regime',    cat: 'tax',    name: 'Old vs New Regime',          desc: 'Full side-by-side comparison',         popular: true  },
  { slug: 'hra-exemption',        cat: 'tax',    name: 'HRA Exemption',              desc: 'Metro & non-metro HRA calc'                           },
  { slug: 'capital-gains-tax',    cat: 'tax',    name: 'Capital Gains Tax',          desc: 'STCG & LTCG on equity, property',      popular: true  },
  { slug: 'tds-calculator',       cat: 'tax',    name: 'TDS Calculator',             desc: 'Sec 194A, 194C, 194H, 194J & more'                    },
  { slug: 'advance-tax',          cat: 'tax',    name: 'Advance Tax',                desc: 'Quarterly payment schedule'                            },
  { slug: 'professional-tax',     cat: 'tax',    name: 'Professional Tax',           desc: 'State-wise PT calculator'                              },
  { slug: 'freelancer-tax',       cat: 'tax',    name: 'Freelancer Tax (44ADA)',      desc: 'Presumptive taxation for professionals'                },
  { slug: 'crypto-tax',           cat: 'tax',    name: 'Crypto Tax',                 desc: '30% flat + 1% TDS on VDA'                              },
  { slug: 'salary-restructuring', cat: 'tax',    name: 'Salary Restructuring',       desc: 'Maximize in-hand pay legally'                          },
  { slug: 'section-80c-planner',  cat: 'tax',    name: '80C Tax Planner',            desc: 'Optimize ₹1.5L deduction'                              },
  { slug: 'section-80d',          cat: 'tax',    name: '80D Tax Benefit',            desc: 'Health insurance deduction'                            },
  { slug: 'section-24b',          cat: 'tax',    name: 'Section 24B',                desc: 'Home loan interest deduction ₹2L'                      },
  { slug: 'nri-tax',              cat: 'tax',    name: 'NRI Tax Calculator',         desc: 'Tax on India income for NRIs'                          },
  { slug: 'esop-tax',             cat: 'tax',    name: 'ESOP / RSU Tax',             desc: 'Tax on employee stock options'                         },
  { slug: 'arrears-relief',       cat: 'tax',    name: 'Arrears Relief (89(1))',      desc: 'Tax relief on salary arrears'                          },
  { slug: 'interest-234abc',      cat: 'tax',    name: 'Interest 234A/B/C',          desc: 'Late filing & payment interest'                        },
  { slug: 'sec-54-exemption',     cat: 'tax',    name: 'Section 54 Exemption',       desc: 'Capital gains on property sale'                        },
  { slug: 'section-80g',          cat: 'tax',    name: '80G Donation Deduction',     desc: 'Tax on donations to NGOs'                              },
  { slug: 'section-80e',          cat: 'tax',    name: '80E Education Loan',         desc: 'Interest deduction on education loan'                  },
  { slug: 'section-80eea',        cat: 'tax',    name: '80EEA First Home Buyer',     desc: 'Extra ₹1.5L deduction for first home'                  },
  { slug: 'section-80gg',         cat: 'tax',    name: '80GG Rent Deduction',        desc: 'For those without HRA component'                       },
  { slug: 'form-15g-15h',         cat: 'tax',    name: 'Form 15G/15H Eligibility',   desc: 'Check if TDS can be avoided'                           },
  { slug: 'perquisite-tax',       cat: 'tax',    name: 'Perquisite Tax',             desc: 'Tax on car, house, ESOP perks'                         },
  { slug: 'gift-tax',             cat: 'tax',    name: 'Gift Tax Calculator',        desc: 'Tax on gifts received'                                 },
  { slug: 'late-filing-penalty',  cat: 'tax',    name: 'Late Filing Penalty',        desc: 'ITR late fee under Sec 234F'                           },
  { slug: 'agriculture-tax',      cat: 'tax',    name: 'Agriculture Income Tax',     desc: 'Partial integration method'                            },
  { slug: 'huf-tax',              cat: 'tax',    name: 'HUF Tax Calculator',         desc: 'Hindu Undivided Family tax'                            },
  { slug: 'presumptive-44ad',     cat: 'tax',    name: 'Presumptive Tax 44AD',       desc: 'For small businesses'                                  },

  // ── LOANS (22) ────────────────────────────────────────────────
  { slug: 'home-loan-emi',        cat: 'loans',  name: 'Home Loan EMI',              desc: 'EMI + amortisation schedule',          popular: true  },
  { slug: 'car-loan-emi',         cat: 'loans',  name: 'Car Loan EMI',               desc: 'Monthly EMI + total interest'                          },
  { slug: 'personal-loan-emi',    cat: 'loans',  name: 'Personal Loan EMI',          desc: 'Instant EMI + comparison'                              },
  { slug: 'education-loan-emi',   cat: 'loans',  name: 'Education Loan EMI',         desc: 'With moratorium period'                                },
  { slug: 'business-loan-emi',    cat: 'loans',  name: 'Business Loan EMI',          desc: 'Term loan for businesses'                              },
  { slug: 'gold-loan-emi',        cat: 'loans',  name: 'Gold Loan EMI',              desc: 'Loan against gold jewellery'                           },
  { slug: 'mudra-loan-emi',       cat: 'loans',  name: 'Mudra Loan EMI',             desc: 'PM Mudra Yojana loan calc'                             },
  { slug: 'loan-eligibility',     cat: 'loans',  name: 'Loan Eligibility',           desc: 'Max loan based on income & FOIR'                       },
  { slug: 'loan-prepayment',      cat: 'loans',  name: 'Loan Prepayment',            desc: 'Interest saved by prepaying'                           },
  { slug: 'balance-transfer',     cat: 'loans',  name: 'Balance Transfer',           desc: 'Savings from BT to lower rate'                         },
  { slug: 'loan-comparison',      cat: 'loans',  name: 'Loan Comparison',            desc: 'Compare 3 loan offers side-by-side'                    },
  { slug: 'debt-snowball',        cat: 'loans',  name: 'Debt Snowball / Avalanche',  desc: 'Fastest way to pay off debt'                           },
  { slug: 'overdraft-interest',   cat: 'loans',  name: 'Overdraft Interest',         desc: 'Daily OD interest calc'                                },
  { slug: 'loan-against-property',cat: 'loans',  name: 'Loan Against Property',      desc: 'LAP eligibility & EMI'                                 },
  { slug: 'two-wheeler-loan',     cat: 'loans',  name: 'Two-Wheeler Loan EMI',       desc: 'Bike loan EMI + total cost'                            },
  { slug: 'moratorium-impact',    cat: 'loans',  name: 'Moratorium Impact',          desc: 'Cost of EMI holiday'                                   },
  { slug: 'credit-card-interest', cat: 'loans',  name: 'Credit Card Interest',       desc: '3.5%/month revolving interest'                         },
  { slug: 'credit-card-payoff',   cat: 'loans',  name: 'Credit Card Payoff',         desc: 'Months to clear card debt'                             },
  { slug: 'credit-card-min-pay',  cat: 'loans',  name: 'Credit Card Min Payment',    desc: 'True cost of paying minimum'                           },
  { slug: 'lease-vs-buy',         cat: 'loans',  name: 'Lease vs Buy',               desc: 'Total cost comparison'                                 },
  { slug: 'top-up-loan',          cat: 'loans',  name: 'Top-Up Loan Calculator',     desc: 'Additional loan on existing home loan'                 },
  { slug: 'joint-loan-tax',       cat: 'loans',  name: 'Joint Loan Tax Benefit',     desc: 'Tax benefits for co-borrowers'                         },

  // ── INVESTMENTS (35) ──────────────────────────────────────────
  { slug: 'sip-calculator',       cat: 'invest', name: 'SIP Calculator',             desc: 'Monthly SIP wealth builder',           popular: true  },
  { slug: 'step-up-sip',         cat: 'invest', name: 'Step-Up SIP',                desc: 'SIP with annual increase'                              },
  { slug: 'lump-sum',             cat: 'invest', name: 'Lump Sum Investment',        desc: 'One-time investment returns'                           },
  { slug: 'swp-calculator',       cat: 'invest', name: 'SWP Calculator',             desc: 'Monthly withdrawal from corpus'                        },
  { slug: 'fd-calculator',        cat: 'invest', name: 'Fixed Deposit',              desc: 'FD maturity with TDS',                 popular: true  },
  { slug: 'rd-calculator',        cat: 'invest', name: 'Recurring Deposit',          desc: 'Monthly RD returns'                                    },
  { slug: 'ppf-calculator',       cat: 'invest', name: 'PPF Calculator',             desc: '15-year PPF with extension',           popular: true  },
  { slug: 'epf-calculator',       cat: 'invest', name: 'EPF Calculator',             desc: 'Retirement corpus from PF'                             },
  { slug: 'nps-calculator',       cat: 'invest', name: 'NPS Calculator',             desc: 'Pension corpus + annuity'                              },
  { slug: 'sukanya-samriddhi',    cat: 'invest', name: 'Sukanya Samriddhi Yojana',   desc: 'SSY for girl child savings'                            },
  { slug: 'atal-pension-yojana',  cat: 'invest', name: 'Atal Pension Yojana',        desc: 'APY contribution & pension'                            },
  { slug: 'scss-calculator',      cat: 'invest', name: 'SCSS Calculator',            desc: 'Senior citizen savings scheme'                         },
  { slug: 'nsc-calculator',       cat: 'invest', name: 'NSC Calculator',             desc: '5-year National Savings Certificate'                   },
  { slug: 'kvp-calculator',       cat: 'invest', name: 'Kisan Vikas Patra',          desc: 'Double your money calculator'                          },
  { slug: 'post-office-mis',      cat: 'invest', name: 'Post Office MIS',            desc: 'Monthly income scheme returns'                         },
  { slug: 'elss-vs-fd-vs-ppf',    cat: 'invest', name: 'ELSS vs FD vs PPF',         desc: 'Best 80C investment comparison'                        },
  { slug: 'compound-interest',    cat: 'invest', name: 'Compound Interest',          desc: 'CI with frequency options'                             },
  { slug: 'cagr-calculator',      cat: 'invest', name: 'CAGR Calculator',            desc: 'Compound annual growth rate'                           },
  { slug: 'xirr-calculator',      cat: 'invest', name: 'XIRR Calculator',            desc: 'Actual MF / SIP returns'                               },
  { slug: 'retirement-corpus',    cat: 'invest', name: 'Retirement Corpus',          desc: 'How much you need to retire',          popular: true  },
  { slug: 'goal-savings',         cat: 'invest', name: 'Goal-Based Savings',         desc: 'Save for a specific goal'                              },
  { slug: 'inflation-impact',     cat: 'invest', name: 'Inflation Impact',           desc: 'Real value of money over time'                         },
  { slug: 'roi-calculator',       cat: 'invest', name: 'ROI Calculator',             desc: 'Return on investment'                                  },
  { slug: 'rule-of-72',           cat: 'invest', name: 'Rule of 72',                 desc: 'Doubling time calculator'                              },
  { slug: 'bond-yield',           cat: 'invest', name: 'Bond Yield / YTM',           desc: 'Yield to maturity on bonds'                            },
  { slug: 'dividend-yield',       cat: 'invest', name: 'Dividend Yield',             desc: 'Stock dividend return'                                 },
  { slug: 'gratuity-calculator',  cat: 'invest', name: 'Gratuity Calculator',        desc: '15/26 formula for private & govt'                      },
  { slug: 'leave-encashment',     cat: 'invest', name: 'Leave Encashment',           desc: 'Tax on leave encashment'                               },
  { slug: 'vpf-calculator',       cat: 'invest', name: 'VPF Calculator',             desc: 'Voluntary PF contribution'                             },
  { slug: 'eps-pension',          cat: 'invest', name: 'EPS Pension (EPFO)',         desc: 'Employee pension scheme'                               },
  { slug: 'stp-calculator',       cat: 'invest', name: 'STP Calculator',             desc: 'Systematic Transfer Plan'                              },
  { slug: 'mf-expense-ratio',     cat: 'invest', name: 'MF Expense Ratio Impact',    desc: 'Cost drag on mutual fund returns'                      },
  { slug: 'mf-exit-load',         cat: 'invest', name: 'Exit Load Calculator',       desc: 'Exit charge on MF redemption'                         },
  { slug: 'reits-returns',        cat: 'invest', name: 'REITs / InvITs Returns',     desc: 'Real estate investment trusts'                         },
  { slug: 'pf-withdrawal-tax',    cat: 'invest', name: 'PF Withdrawal Tax',          desc: 'Tax if withdrawn before 5 years'                       },

  // ── INSURANCE (10) ────────────────────────────────────────────
  { slug: 'term-insurance',       cat: 'insurance', name: 'Term Insurance Cover',    desc: 'How much cover do you need?'                           },
  { slug: 'health-insurance',     cat: 'insurance', name: 'Health Insurance',        desc: 'Cover needed vs premium'                               },
  { slug: 'life-insurance',       cat: 'insurance', name: 'Life Insurance Maturity', desc: 'Policy returns calculator'                             },
  { slug: 'motor-insurance',      cat: 'insurance', name: 'Motor Insurance',         desc: 'IDV and premium estimator'                             },
  { slug: 'ulip-returns',         cat: 'insurance', name: 'ULIP Returns',            desc: 'Net returns after charges'                             },
  { slug: 'human-life-value',     cat: 'insurance', name: 'Human Life Value',        desc: 'Economic value of your life'                           },
  { slug: 'critical-illness',     cat: 'insurance', name: 'Critical Illness Cover',  desc: 'Corpus needed for critical illness'                    },
  { slug: 'premium-affordability',cat: 'insurance', name: 'Premium Affordability',   desc: 'Budget for insurance premium'                          },
  { slug: 'trop-vs-term',         cat: 'insurance', name: 'TROP vs Pure Term',       desc: 'Return of premium comparison'                          },
  { slug: 'pension-plan',         cat: 'insurance', name: 'Pension Plan Returns',    desc: 'Insurance pension plan calculator'                     },

  // ── REAL ESTATE (10) ──────────────────────────────────────────
  { slug: 'stamp-duty',           cat: 'realty', name: 'Stamp Duty Calculator',      desc: 'State-wise stamp duty & registration', popular: true  },
  { slug: 'rent-vs-buy',          cat: 'realty', name: 'Rent vs Buy',                desc: 'Full financial analysis'                               },
  { slug: 'pmay-subsidy',         cat: 'realty', name: 'PMAY Subsidy',               desc: 'Pradhan Mantri Awas Yojana benefit'                     },
  { slug: 'rental-yield',         cat: 'realty', name: 'Rental Yield',               desc: 'ROI on rental property'                                },
  { slug: 'construction-cost',    cat: 'realty', name: 'Construction Cost',          desc: 'Cost per sq ft estimator'                              },
  { slug: 'property-tax',         cat: 'realty', name: 'Property Tax',               desc: 'Annual property tax estimate'                          },
  { slug: 'area-converter',       cat: 'realty', name: 'Area Converter',             desc: 'Sq ft, sq m, cents, acres, guntas'                     },
  { slug: 'indexation-benefit',   cat: 'realty', name: 'Indexation Benefit',         desc: 'Indexed cost for LTCG'                                 },
  { slug: 'registration-charges', cat: 'realty', name: 'Registration Charges',       desc: 'Property registration fee'                             },
  { slug: 'home-renovation',      cat: 'realty', name: 'Home Renovation Budget',     desc: 'Cost of renovation per sq ft'                          },

  // ── BUSINESS & GST (20) ───────────────────────────────────────
  { slug: 'gst-calculator',       cat: 'business', name: 'GST Calculator',           desc: 'Add / remove GST instantly',           popular: true  },
  { slug: 'gst-invoice',          cat: 'business', name: 'GST Invoice / ITC',        desc: 'Input tax credit calculation'                          },
  { slug: 'gst-late-fee',         cat: 'business', name: 'GST Late Fee & Interest',  desc: 'GSTR-3B late filing charges'                           },
  { slug: 'gst-composition',      cat: 'business', name: 'GST Composition Scheme',   desc: 'Tax for small businesses'                              },
  { slug: 'profit-loss',          cat: 'business', name: 'Profit & Loss',            desc: 'Revenue, cost, net profit'                             },
  { slug: 'breakeven',            cat: 'business', name: 'Breakeven Point',          desc: 'Units to cover fixed costs'                            },
  { slug: 'markup-vs-margin',     cat: 'business', name: 'Markup vs Margin',         desc: 'Pricing calculator'                                    },
  { slug: 'working-capital',      cat: 'business', name: 'Working Capital',          desc: 'Short-term liquidity'                                  },
  { slug: 'import-duty',          cat: 'business', name: 'Import Duty',              desc: 'Custom duty + IGST on imports'                         },
  { slug: 'depreciation',         cat: 'business', name: 'Depreciation (SLM/WDV)',   desc: 'Asset depreciation calc'                               },
  { slug: 'partnership-profit',   cat: 'business', name: 'Partnership Profit Share', desc: 'Profit sharing ratio'                                  },
  { slug: 'esic-calculator',      cat: 'business', name: 'ESIC Calculator',          desc: 'Employee state insurance'                              },
  { slug: 'pf-wages',             cat: 'business', name: 'PF Wages Calculator',      desc: 'PF on actual vs ceiling wages'                         },
  { slug: 'bonus-calculator',     cat: 'business', name: 'Bonus Calculator',         desc: 'Statutory bonus calc'                                  },
  { slug: 'notice-period',        cat: 'business', name: 'Notice Period Recovery',   desc: 'Buyout amount calculation'                             },
  { slug: 'cash-flow',            cat: 'business', name: 'Cash Flow Estimator',      desc: 'Monthly business cash flow'                            },
  { slug: 'roe-roce',             cat: 'business', name: 'ROE / ROCE Calculator',    desc: 'Return on equity & capital'                            },
  { slug: 'msme-loan',            cat: 'business', name: 'MSME Loan Eligibility',    desc: 'MSME scheme loan check'                                },
  { slug: 'freelancer-income',    cat: 'business', name: 'Freelancer Income',        desc: 'Project fee & tax estimator'                           },
  { slug: 'tds-due-date',         cat: 'business', name: 'TDS Due Date Finder',      desc: 'When to deposit TDS'                                   },

  // ── UTILITY & LIFESTYLE (20) ──────────────────────────────────
  { slug: 'emergency-fund',       cat: 'utility', name: 'Emergency Fund',            desc: '6-month safety net calculator'                         },
  { slug: 'net-worth',            cat: 'utility', name: 'Net Worth Calculator',      desc: 'Assets minus liabilities'                              },
  { slug: 'budget-planner',       cat: 'utility', name: 'Budget Planner',            desc: '50/30/20 rule budget'                                  },
  { slug: 'emi-affordability',    cat: 'utility', name: 'EMI Affordability',         desc: 'Max EMI based on salary'                               },
  { slug: 'salary-hike',          cat: 'utility', name: 'Salary Hike Impact',        desc: '% hike to monthly change'                              },
  { slug: 'electricity-bill',     cat: 'utility', name: 'Electricity Bill',          desc: 'Monthly units to bill amount'                          },
  { slug: 'fuel-cost',            cat: 'utility', name: 'Fuel Cost Calculator',      desc: 'Monthly fuel expense'                                  },
  { slug: 'age-calculator',       cat: 'utility', name: 'Age / Days Counter',        desc: 'Exact age and days lived'                              },
  { slug: 'tip-calculator',       cat: 'utility', name: 'Tip Calculator',            desc: 'Tip + split bill'                                      },
  { slug: 'currency-converter',   cat: 'utility', name: 'Currency Converter',        desc: 'Live ₹ to USD/EUR/GBP'                                 },
  { slug: 'unit-converter',       cat: 'utility', name: 'Unit Converter',            desc: 'Length, weight, area, temp'                            },
  { slug: 'cost-of-living',       cat: 'utility', name: 'Cost of Living',            desc: 'City comparison calculator'                            },
  { slug: 'financial-health',     cat: 'utility', name: 'Financial Health Score',    desc: 'Rate your financial fitness'                           },
  { slug: 'fire-number',          cat: 'utility', name: 'FIRE Number Calculator',    desc: 'Financial independence target'                         },
  { slug: 'coast-fire',           cat: 'utility', name: 'Coast FIRE Calculator',     desc: 'When to stop adding to corpus'                         },
  { slug: 'debt-to-income',       cat: 'utility', name: 'Debt-to-Income Ratio',      desc: 'Loan burden on income'                                 },
  { slug: 'ev-vs-petrol',         cat: 'utility', name: 'EV vs Petrol Cost',         desc: 'Total ownership cost comparison'                       },
  { slug: 'wedding-budget',       cat: 'utility', name: 'Wedding Budget',            desc: 'Plan your wedding expenses'                            },
  { slug: 'savings-rate',         cat: 'utility', name: 'Savings Rate Calculator',   desc: 'Income vs savings benchmark'                           },
  { slug: 'home-renovation-cost', cat: 'utility', name: 'Home Renovation Budget',    desc: 'Room-wise renovation cost'                             },

  // ── NRI (14) ──────────────────────────────────────────────────
  { slug: 'nri-income-tax',       cat: 'nri', name: 'NRI Income Tax',                desc: 'Tax on India income for NRIs'                          },
  { slug: 'dtaa-benefit',         cat: 'nri', name: 'DTAA Benefit Calculator',       desc: 'Double tax treaty savings'                             },
  { slug: 'remittance',           cat: 'nri', name: 'Remittance Calculator',         desc: 'Send money to India'                                   },
  { slug: 'nre-nro-fd',           cat: 'nri', name: 'NRE vs NRO FD',                desc: 'Which account is better?'                              },
  { slug: 'fcnr-returns',         cat: 'nri', name: 'FCNR Returns',                  desc: 'Foreign currency NR deposit'                           },
  { slug: 'wire-transfer-fee',    cat: 'nri', name: 'Wire Transfer Fee',             desc: 'Compare remittance costs'                              },
  { slug: 'forex-gain-loss',      cat: 'nri', name: 'Forex Gain / Loss',             desc: 'Currency exchange P&L'                                 },
  { slug: 'nri-home-loan',        cat: 'nri', name: 'NRI Home Loan',                 desc: 'Eligibility + EMI for NRIs'                            },
  { slug: 'repatriation',         cat: 'nri', name: 'Repatriation Calculator',       desc: 'Funds you can send abroad'                             },
  { slug: 'lrs-limit',            cat: 'nri', name: 'LRS Limit Calculator',          desc: '$250K/yr limit usage'                                  },
  { slug: 'nri-ppf',              cat: 'nri', name: 'NRI PPF Rules',                 desc: 'Existing PPF for NRIs'                                 },
  { slug: 'return-to-india',      cat: 'nri', name: 'Return to India Planner',       desc: 'Financial checklist'                                   },
  { slug: 'oci-tax',              cat: 'nri', name: 'OCI Card Holder Tax',           desc: 'Tax rules for OCI holders'                             },
  { slug: 'nri-capital-gains',    cat: 'nri', name: 'NRI Capital Gains',             desc: 'TDS on NRI property sale'                              },

  // ── STOCKS & TRADING (15) ─────────────────────────────────────
  { slug: 'brokerage',            cat: 'stocks', name: 'Brokerage Calculator',       desc: 'Zerodha / ICICI / Groww charges'                       },
  { slug: 'stt-ctt',              cat: 'stocks', name: 'STT / CTT Calculator',       desc: 'Securities transaction tax'                            },
  { slug: 'fno-pnl',              cat: 'stocks', name: 'F&O Profit/Loss',            desc: 'Futures & options P&L'                                 },
  { slug: 'options-premium',      cat: 'stocks', name: 'Options Premium',            desc: 'Basic BSM options pricing'                             },
  { slug: 'pe-ratio',             cat: 'stocks', name: 'P/E Ratio Estimator',        desc: 'Stock valuation checker'                               },
  { slug: 'dcf-valuation',        cat: 'stocks', name: 'Intrinsic Value (DCF)',       desc: 'Discounted cash flow'                                  },
  { slug: 'dividend-reinvest',    cat: 'stocks', name: 'Dividend Reinvestment',      desc: 'DRIP returns calculator'                               },
  { slug: 'short-selling',        cat: 'stocks', name: 'Short Selling P&L',          desc: 'Short position profit/loss'                            },
  { slug: 'portfolio-rebalance',  cat: 'stocks', name: 'Portfolio Rebalancing',      desc: 'Target allocation calculator'                          },
  { slug: 'risk-return',          cat: 'stocks', name: 'Risk-Return Ratio',          desc: 'Sharpe ratio estimator'                                },
  { slug: 'sgb-returns',          cat: 'stocks', name: 'Sovereign Gold Bond',        desc: 'SGB returns + tax benefit'                             },
  { slug: 'ipo-allotment',        cat: 'stocks', name: 'IPO Allotment Estimator',    desc: 'Chances of IPO allotment'                              },
  { slug: 'rights-issue',         cat: 'stocks', name: 'Rights Issue Calculator',    desc: 'Rights issue benefit'                                  },
  { slug: 'bonus-share-impact',   cat: 'stocks', name: 'Bonus Share Impact',         desc: 'Cost after bonus shares'                               },
  { slug: 'esop-pnl',             cat: 'stocks', name: 'ESOP / RSU P&L',            desc: 'Effective gain after tax'                              },

  // ── GOVT SCHEMES (10) ─────────────────────────────────────────
  { slug: 'pm-kisan',             cat: 'govt', name: 'PM Kisan Benefit',             desc: '₹6000/yr farmer benefit'                               },
  { slug: 'pmay-rural',           cat: 'govt', name: 'PMAY Rural Subsidy',           desc: 'Rural housing benefit'                                 },
  { slug: 'pm-jeevan-jyoti',      cat: 'govt', name: 'PM Jeevan Jyoti Bima',        desc: '₹2L cover at ₹436/yr'                                  },
  { slug: 'pm-suraksha-bima',     cat: 'govt', name: 'PM Suraksha Bima',            desc: '₹2L accidental cover ₹20/yr'                           },
  { slug: 'ayushman-bharat',      cat: 'govt', name: 'Ayushman Bharat',             desc: 'PM-JAY ₹5L health cover check'                         },
  { slug: 'mudra-scheme',         cat: 'govt', name: 'PM Mudra Scheme',             desc: 'Shishu/Kishore/Tarun loan'                             },
  { slug: 'standup-india',        cat: 'govt', name: 'Stand Up India',              desc: 'SC/ST/women entrepreneur loan'                         },
  { slug: 'jan-dhan',             cat: 'govt', name: 'Jan Dhan Benefits',           desc: 'PMJDY account benefits'                                },
  { slug: 'svamitva-scheme',      cat: 'govt', name: 'SVAMITVA Scheme',             desc: 'Property rights in villages'                           },
  { slug: 'startup-india',        cat: 'govt', name: 'Startup India Benefits',      desc: 'Tax exemptions for startups'                           },

  // ── EDUCATION & CAREER (12) ───────────────────────────────────
  { slug: 'education-corpus',     cat: 'education', name: 'Education Corpus',        desc: 'Save for child education'                              },
  { slug: 'study-abroad-cost',    cat: 'education', name: 'Cost of Studying Abroad', desc: 'USA/UK/Canada/Australia'                               },
  { slug: 'education-loan-elig',  cat: 'education', name: 'Education Loan Eligibility',desc: 'Bank loan for studies'                              },
  { slug: 'mba-roi',              cat: 'education', name: 'MBA ROI Calculator',       desc: 'Return on MBA investment'                             },
  { slug: 'career-income-growth', cat: 'education', name: 'Career Income Growth',    desc: 'Salary projections over years'                         },
  { slug: 'coaching-roi',         cat: 'education', name: 'Coaching ROI',            desc: 'Value of coaching institute'                           },
  { slug: 'scholarship-calc',     cat: 'education', name: 'Scholarship Calculator',  desc: 'How scholarship cuts your loan'                        },
  { slug: 'hostel-vs-day',        cat: 'education', name: 'Hostel vs Day Scholar',   desc: 'Total cost comparison'                                 },
  { slug: 'neet-prep-cost',       cat: 'education', name: 'NEET/JEE Prep Cost',     desc: 'Total coaching investment'                             },
  { slug: 'upskilling-roi',       cat: 'education', name: 'Upskilling ROI',          desc: 'Return on course investment'                           },
  { slug: 'internship-value',     cat: 'education', name: 'Internship Value',        desc: 'Stipend vs learning trade-off'                         },
  { slug: 'salary-negotiation',   cat: 'education', name: 'Salary Negotiation',      desc: 'Counter-offer calculator'                              },

  // ── CREDIT & CARDS (10) ───────────────────────────────────────
  { slug: 'credit-score-impact',  cat: 'credit', name: 'Credit Score Impact',       desc: 'How actions affect CIBIL'                              },
  { slug: 'credit-utilization',   cat: 'credit', name: 'Credit Utilization',        desc: 'Keep below 30% for best score'                         },
  { slug: 'rewards-points-value', cat: 'credit', name: 'Rewards Points Value',      desc: 'How much are your points worth?'                       },
  { slug: 'cashback-calculator',  cat: 'credit', name: 'Cashback Calculator',       desc: 'Annual cashback from spending'                         },
  { slug: 'card-vs-emi',          cat: 'credit', name: 'Card vs No-Cost EMI',       desc: 'True cost comparison'                                  },
  { slug: 'annual-fee-breakeven', cat: 'credit', name: 'Annual Fee Breakeven',      desc: 'Is premium card worth it?'                             },
  { slug: 'foreign-txn-fee',      cat: 'credit', name: 'Foreign Transaction Fee',   desc: 'Cost of using card abroad'                             },
  { slug: 'card-vs-personal-loan',cat: 'credit', name: 'Card Loan vs Personal Loan',desc: 'Cheaper borrowing option'                             },
  { slug: 'card-upgrade-elig',    cat: 'credit', name: 'Card Upgrade Eligibility',  desc: 'When to upgrade your card'                             },
  { slug: 'cibil-simulator',      cat: 'credit', name: 'CIBIL Score Simulator',     desc: 'Estimate score improvements'                           },

  // ── INTERNATIONAL (20) ────────────────────────────────────────
  { slug: 'us-income-tax',        cat: 'intl', name: 'US Income Tax (for NRIs)',     desc: 'Federal tax estimate'                                  },
  { slug: 'us-401k',              cat: 'intl', name: 'US 401(k) Calculator',         desc: 'Retirement savings in USA'                             },
  { slug: 'us-mortgage',          cat: 'intl', name: 'US Mortgage / EMI',            desc: '30yr/15yr mortgage calc'                               },
  { slug: 'us-capital-gains',     cat: 'intl', name: 'US Capital Gains Tax',         desc: 'Short & long term CG'                                  },
  { slug: 'us-social-security',   cat: 'intl', name: 'US Social Security',           desc: 'Benefit estimate calculator'                           },
  { slug: 'uk-income-tax',        cat: 'intl', name: 'UK Income Tax',                desc: 'PAYE tax for UK residents'                             },
  { slug: 'uk-pension',           cat: 'intl', name: 'UK Pension Calculator',        desc: 'State + workplace pension'                             },
  { slug: 'uae-tax',              cat: 'intl', name: 'UAE Tax Calculator',           desc: 'Zero income tax check + VAT'                           },
  { slug: 'canada-rrsp',          cat: 'intl', name: 'Canada RRSP Calculator',       desc: 'Registered retirement savings'                         },
  { slug: 'australia-super',      cat: 'intl', name: 'Australia Superannuation',     desc: 'Super fund returns'                                    },
  { slug: 'singapore-cpf',        cat: 'intl', name: 'Singapore CPF',               desc: 'Central provident fund calc'                           },
  { slug: 'germany-income-tax',   cat: 'intl', name: 'Germany Income Tax',           desc: 'Steuerklasse tax estimate'                             },
  { slug: 'vat-calculator',       cat: 'intl', name: 'VAT Calculator (EU/UAE)',      desc: 'Value added tax calc'                                  },
  { slug: 'dca-calculator',       cat: 'intl', name: 'Dollar Cost Averaging',        desc: 'DCA vs lump sum comparison'                            },
  { slug: 'us-f1-h1b-tax',        cat: 'intl', name: 'F-1 / H-1B Tax (US)',         desc: 'Student & work visa taxes'                             },
  { slug: 'global-inflation',     cat: 'intl', name: 'Global Inflation Calculator',  desc: 'Purchasing power by country'                           },
  { slug: 'ppp-converter',        cat: 'intl', name: 'PPP Converter',               desc: 'Purchasing power parity'                               },
  { slug: 'intl-fd-rates',        cat: 'intl', name: 'International FD Rates',       desc: 'India vs global FD returns'                            },
  { slug: 'cross-border-tax',     cat: 'intl', name: 'Cross-Border Tax',            desc: 'Income in 2 countries'                                 },
  { slug: 'canada-income-tax',    cat: 'intl', name: 'Canada Income Tax',            desc: 'Federal + provincial tax'                              },
]

// Helper: get by slug
export function getCalc(slug) {
  return CALCULATORS.find(c => c.slug === slug)
}

// Helper: get by category
export function getByCategory(catId) {
  return CALCULATORS.filter(c => c.cat === catId)
}

// Helper: get popular
export function getPopular() {
  return CALCULATORS.filter(c => c.popular)
}

// Related calculators (by category, excluding current)
export function getRelated(slug, limit = 3) {
  const current = getCalc(slug)
  if (!current) return []
  return CALCULATORS.filter(c => c.cat === current.cat && c.slug !== slug).slice(0, limit)
}
